FROM jenkins/jenkins:lts

USER root

# Install Docker + kubectl
RUN apt-get update && \
    apt-get install -y docker.io curl ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install kubectl
RUN curl -L -o /usr/local/bin/kubectl \
    https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x /usr/local/bin/kubectl
